// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Client struct {
	Cpf     string `json:"cpf"`
	Nome    string `json:"nome"`
	Celular string `json:"celular"`
}

type Dados struct {
	Celular          string    `json:"celular"`
	Nucpf            string    `json:"nucpf"`
	Nomesegurado     string    `json:"nomesegurado"`
	Dtnascimento     string    `json:"dtnascimento"`
	Esp              string    `json:"esp"`
	Vlbeneficio      string    `json:"vlbeneficio"`
	Idbancopagto     string    `json:"idbancopagto"`
	Idagenciabanco   string    `json:"idagenciabanco"`
	Nucontacorrente  string    `json:"nucontacorrente"`
	Idbancoempres    string    `json:"idbancoempres"`
	Idcontratoempres string    `json:"idcontratoempres"`
	Vlempres         string    `json:"vlempres"`
	Compinidesconto  string    `json:"compinidesconto"`
	Compfimdesconto  string    `json:"compfimdesconto"`
	Quantparcelas    string    `json:"quantparcelas"`
	Vlparcela        string    `json:"vlparcela"`
	Endereco         string    `json:"endereco"`
	Bairro           string    `json:"bairro"`
	Municipio        string    `json:"municipio"`
	Uf               string    `json:"uf"`
	Cep              string    `json:"cep"`
	Cel              string    `json:"CEL"`
	Fone1            string    `json:"FONE1"`
	Fone2            string    `json:"FONE2"`
	Fone3            string    `json:"FONE3"`
	Idade            string    `json:"idade"`
	Clients          []*Client `json:"clients"`
}
